name: PandoSabor
version: '1.0-SNAPSHOT'
main: pando.org.pandoSabor.PandoSabor
api-version: '1.21'

commands:
  cobrar:
    description: Comando principal de cobrar.
    usage: /<command>
  model:
    description: Comando principal de models.
    usage: /<command>
  boss:
    description: Comando principal de boss.
    usage: /<command>

